name: Pull Request

on:
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          default: true
      - name: Run tests
        run: cargo test --verbose
